---
title: "HW 4 Plotly"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_float: true
---

We are going to take a look at the [Instacart](https://www.instacart.com/datasets/grocery-shopping-2017) dataset!

<br> 


#### Loading in the relevant libraries
```{r setup}
# loading in the relevant libraries
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

<br>

#### Loading in the instacart data set with a random sample of 1000
```{r data_load}
# loading in the instacart data set with a random sample of 1000
instacart_df =
  p8105.datasets::instacart %>% 
  sample_n(1000) %>% 
  janitor::clean_names() %>% 
  mutate(order_id = as.factor(order_id), 
         order_dow = order_dow + 1)

# factor re-level for days
days = c("Sunday", "Monday", "Tuesday", "Wednesday",
          "Thursday", "Friday", "Saturday")
instacart_df$order_dow = days[instacart_df$order_dow]
instacart_df$order_dow = fct_relevel(instacart_df$order_dow,
                                    "Sunday", "Monday", "Tuesday", "Wednesday",
                                    "Thursday", "Friday", "Saturday")
```

## Plotly plots

### Box plot: Order time by department

```{r boxplot, dpi = 300}
# creating a box plot of order time by department
box_ggplot =
  instacart_df %>%  
  ggplot(aes(x = department, y = order_hour_of_day, fill = department)) + 
  geom_boxplot() + 
  coord_flip() +
  theme_bw() + 
  viridis::scale_fill_viridis(discrete = TRUE) + 
  labs(y = "Order hour of day",
       x = "Department") + 
  theme(legend.position = "none")

ggplotly(box_ggplot, height = 600, width = 800)
```

### Bar plot: Number of orders

```{r barchart, dpi = 300}
# changing axis labels
x_lab = list(title = "Department")
y_lab = list(title = "Number of Orders")

# creating a bar plot of number of orders by department
instacart_df %>% 
  group_by(department) %>% 
  summarize(numb_orders = n()) %>% 
  mutate(department = as.factor(department), 
        department = fct_reorder(department, numb_orders)) %>% 
  plot_ly(x = ~department, 
          y = ~numb_orders, 
          color = ~department, 
          type = "bar", 
          colors = "viridis", 
          height = 600, width = 800) %>% 
  layout(xaxis = x_lab, yaxis = y_lab)
```

### Density plot: Order time distribution

```{r density, dpi = 300}
# creating a density plot of order time by order day
density_ggplot =
  instacart_df %>%
  ggplot(aes(x = order_hour_of_day, fill = order_dow)) +
  geom_density(alpha = 0.2) +
  theme_bw() +
  labs(x = "Order hour of day", 
       y = "Denstiy") + 
  viridis::scale_fill_viridis(discrete = TRUE) + 
  guides(fill = guide_legend(title = "Day"))

ggplotly(density_ggplot, height = 600, width = 800)
```
